######################################################################
##
## Filename: messagechunk.udo
## Created on: Wed May 29 3:30:55 AM Eastern Daylight Time 2013
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
